#
#server:
#  port: 8099
#
#spring:
#  thymeleaf:
#    cache : false
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://ec2-mysql-db2.cdmssvujvy8y.ap-northeast-2.rds.amazonaws.com:3306/bootex
#
#    username: jichang23
#    password: dlwlckd12
#
#  jpa:
#    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    #    open-in-view: false
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: create
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
#
#
server:
  port: 8099


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

